[build]
  # Build default untuk local & environment dasar
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.124.1"

# ENVIRONMENT: PRODUCTION
[context.production]
  environment = { HUGO_ENV = "production", HUGO_BASEURL = "https://domain-produksi-anda.com" }

# ENVIRONMENT: BRANCH DEPLOYMENT (misal untuk branch 'development')
[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  environment = { HUGO_ENV = "development" }

# ENVIRONMENT: PULL REQUESTS
[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"
  environment = { HUGO_ENV = "development" }
